### ISSUE TITLE
Could you please update your tutorials to use latest dependency?

### ISSUE THREAD

**Issue by javaHelper** [piomin/sample-spring-microservices#11]

**Comment by ramazansakin** [comment]
Hi @javaHelper,

thats not latest but I upgraded java & spring version. you can review it and I hope it helps you.

https://github.com/ramazansakin/sample-spring-microservices

**Comment by Kordedekehine** [comment]
I should check it

**Comment by piomin** [comment]
This repository is for Spring Boot 1.5. If you need the latest example see that repo: https://github.com/piomin/sample-spring-microservices-new.git
